### ISSUE TITLE
🔹 - Change GetPlayers into a Players property

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/libre-cards-against-humanity#3]
## Summary

In our `ILobby` interface we are exposing a `GetPlayers` method that returns an `IEnumerable<Player>`. It might be a little more convenient to have a `Players` property with only a getter to access this collection.

https://github.com/petrspelos/libre-cards-against-humanity/blob/dd943ab10c2276f2dcd5c1787862c706195ee87c/src/LibreCards.Core/ILobby.cs#L14

## What needs to be done

The `GetPlayers` **method** needs to be changed into a `Players` **property** with only a `{ get; }` (getter) and users of this interface need to be adjusted. ☺️ 

## Interested? ❤️ 

_If you'd like to tackle this issue, make sure to comment below so that multiple people don't work on the same issue accidentally._ 🌮

**Comment by Jayita10** [comment]
I would like to work on this issue

**Comment by petrspelos** [comment]
Heya, @Jayita10! 

Absolutely. ☺️ 

Go right ahead. Let me know if you need any more info or if you have any questions. 👍

**Comment by Jayita10** [comment]
Hi @petrspelos, please review my work. Thanks :)

**Comment by petrspelos** [comment]
Fixed, thank you for contributing. ☺️
