### ISSUE TITLE
🔶 - Implement ICardRepository

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/libre-cards-against-humanity#4]
## Summary

Our [ICardRepository](https://github.com/petrspelos/libre-cards-against-humanity/blob/main/src/LibreCards.Core/ICardRepository.cs) currently does not have a real implementation.

## What needs to be done

Create an implementation of [ICardRepository](https://github.com/petrspelos/libre-cards-against-humanity/blob/main/src/LibreCards.Core/ICardRepository.cs) that uses `/src/LibreCards.Core/default-cards.json` as the card source.

## Interested? ❤️ 

_If you'd like to tackle this issue, make sure to comment below so that multiple people don't work on the same issue accidentally._ 🌮

**Comment by tomalop** [comment]
✋ I'd like to be assigned to this one

**Comment by petrspelos** [comment]
You got it, chief! 🥇
